#!/usr/bin/bash
# pkhex for linux and macosx
# require wine or wine-stable or winehq-stable 9.0 or + and winetricks 20240105 or +
XDG_DATA_HOME="/opt"
PKHEX_DATA_DIRECTORY="/opt/pkhex"
export WINEDEBUG="${WINEDEBUG--all}"
export WINEPREFIX="/opt/pkhex/prefix"
#this require for net 7 and net 8 or error
export DOTNET_ROOT="C:\Program Files\dotnet"
#this require for net 7 and net 8 or error
export DOTNET_BUNDLE_EXTRACT_BASE_DIR="C:\dotnet_bundle_extract"

if [ ! -d "$PKHEX_DATA_DIRECTORY" ]; then
  wget "https://github.com/amidevous/PKHeX/raw/master/update.sh" -qO update.sh
  chmod +x update.sh
  ./update.sh
  rm -f update.sh
  exit
fi

case "$1" in
  'kill')
    wineserver -k "$2"
    ;;
  'winetricks')
    shift 1
    winetricks "$@"
    ;;
  'wine')
    shift 1
    wine "$@"
    ;;
  '-h'|'--help'|'help')
    echo 'Usage:'
    printf '%s [command]\t\t\tRun PKHeX (with optional command)\n' "$(basename "$0")"
    printf '%s kill [n]\t\t\tKill PKHeX (optinally with signal n)\n' "$(basename "$0")"
    printf '%s wine [command]\t\tExecute Wine command on the Wine prefix (winecfg, regedit, ...)\n' "$(basename "$0")"
    printf '%s winetricks [command]\t\tExecute Winetricks command on the Wine prefix\n' "$(basename "$0")"
    printf '%s {-h --help help}\t\tDisplay this help\n' "$(basename "$0")"
    ;;
  'update')
    echo 'Updating'
    wget "https://github.com/amidevous/PKHeX/raw/master/update.sh" -qO update.sh
    chmod +x update.sh
    ./update.sh
    rm -f update.sh
    ;;
  *)
    cd ${PKHEX_DATA_DIRECTORY}
    rm -f cfg.json
    /opt/pkhex/bin/wine PKHeX.exe "$@"
    /opt/pkhex/bin/wineserver -w
    ;;
esac
